project:
  type: website
  output-dir: docs
  resources: 
    - "img/" 

website:
  title: "CSUCI Datathon"
  repo-url: https://github.com/inqs909/ci_datathon_25
  site-url: www.inqs.info/ci_datathon_25
  navbar:
    right:
      - text: "Tutorial"
        href: tutorial.qmd
      - text: "Competition"
        href: competition.qmd
      - text: "Databook"
        href: codebook.qmd


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true


    



