project:
  type: website
  output-dir: docs

website:
  title: "CSUCI Datathon"
  repo-url: https://github.com/inqs909/ci_datathon_25
  site-url: www.inqs.info/ci_datathon_25
  navbar:
    right:
      - text: "Tutorial"
        href: tutorial.qmd


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true


    



